### PR TITLE
Fix #9 : add auto build via docker-compose

### LINKED ISSUE #9: Pb docker-compose
I'm facing this docker-compose problem even if I'm using the config file as is on git.
I'm running on Boot2Docker-cli version: v1.7.0 on Mac OS.

```
➜  docker-symfony git:(master) docker-compose up  
Pulling application (symfony/code:latest)...
Pulling repository symfony/code
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
```

Do you have any ideas?

### PR DESCRIPTION
**Pull request by B-Galati**
fix #9

Images are automatically built when `docker-compose up` is called

### CODE REVIEW

**Comment by eko** [comment]
Hi @B-Galati,

Can you also update the `.travis.yml` file to use `docker-compose build` please?

Thank you for this fix!

**Comment by eko** [comment]
Thank you @B-Galati :+1:

**Comment by B-Galati** [comment]
Hello @eko !

I updated `.travis.yml` but CI failed for an unknown reason to me..

Thanks for the merge ;)

**Comment by eko** [comment]
I've seen that @B-Galati, I know this is not due to your additions as `docker-compose up` is running well but exit for an unknown reason.

I will try to investigate on this.

Thank you for your work, this is a great merge :)

**Pull request merged**
