### PR TITLE
Issue with php-fpm (already created www pool ?)

### PR DESCRIPTION
**Pull request by bobman38**

### CODE REVIEW

**Comment by Draed** [comment]
Hello ,

Is this commit resolve the problem ? (I ask because it does't for me :-/ )
I don't understand why you have changed the port (9000->9001) ?
By the way, the php-fpm dockerfile still expose the 9000 port (forgot or not ?)

**Comment by bobman38** [comment]
It seems that there is already a www pool created on port 9000 but only for localhost. That's why I have set the 9001 port... (on both php-fpm & nginx) Still working on that..

**Comment by eko** [comment]
Hi @bobman38,

I agree with this fix in `php-fpm/Dockerfile` but can we please keep port `9000` which is the default php-fpm port? If you have a conflict with this port, you can modify it locally, but for this sandbox, I prefer to keep default ports.

Thank you

**Comment by CarstenHoyer** [comment]
I got around different issues, including these, from using the official PHP image as base. I have a feature branch, that works with PHP7. It also works with the PHP5 fpm alpine image, and the setup from docker-symfony. Except for the symfony.ini part.

I am not going to make a pull request, since this is PHP 7 and I also make some other assumptions. But have a look.

https://github.com/CarstenHoyer/docker-symfony/blob/e7cee3cb047db56d90a9ee62941d86778d515961/php-fpm/Dockerfile

**Comment by ozsk** [comment]
@bobman38 

There is a problem with this PR. Probably changes in php-fpm user and group caused PHP exception:
`FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)`

Did I miss something with priviliges?

**Comment by Kalyse** [comment]
Strange, but i had the same errors, I had to switch to port 9001. No idea why...

**Pull request merged**
